server:
  port: 8001

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/peterdyf/SpringCloudSamples
          searchPaths: data
  rabbitmq:
     addresses: localhost:5672
     adminAddresses: http://localhost:15672
     nodes: rabbit@localhost
     username: guest
     password: guest