server:
  port: 8003

eureka:
 client:
   registerWithEureka: false
   fetchRegistry: false
   serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
   server:
      waitTimeInMsWhenSyncEmpty: 0